package main

var techInterests = []string{
	"Inteligência Artificial",
	"LLMs",
	"RAG",
	"Embeddings",
	"Vector Databases",
	"pgvector",
	"AI Agents",
	"Multi-Agent Systems",
	"Reranking",
	"Context Engineering",
	"AI Engineering",
	"AI-assisted Software Development",

	"Arquitetura de Software",
	"System Design",
	"Sistemas Distribuídos",
	"Concorrência",
	"Paralelismo",
	"Escalabilidade",
	"Alta Disponibilidade",
	"Tolerância a Falhas",
	"Load Balancing",
	"Caching",
	"Filas e processamento assíncrono",
	"Event-Driven Architecture",
	"Arquitetura Orientada a Eventos",
	"Distributed Systems",
	"Performance",
	"Otimização",
	"Modelagem de Dados",
	"Banco de Dados",
	"Consistência e Transações",
	"Locks e Concorrência",
	"Observabilidade",

	"Engenharia de Software",
	"Design Patterns",
	"Clean Code",
	"Simplicidade de Software",
	"Manutenibilidade",
	"Legacy Modernization",
	"Refatoração",
	"Trade-offs arquiteturais",
	"Complexidade de Software",
	"Developer Experience",

	"Compiladores",
	"Linguagens de Programação",
	"AST",
	"Parsing",
	"Tree-sitter",
}
